server:
  port: 8762

## Eureka Config
eureka:
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka_url:https://eureka-production-534a.up.railway.app/eureka}

## Spring Config
spring:
  application:
    name: CloudGateway
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          "[/**]": ## For all routes
            allowedOrigins: "*" ## ${ALLOWED_ORIGINS}
            allowedHeaders: "*"
            allowedMethos:
              - GET
              - POST

## Habilitating API Actuator to access /actuator/gateway/routes
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - "*"
